<?xml version='1.1' encoding='UTF-8'?>
<build>
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UpstreamCause>
            <upstreamProject>java-deploy-job</upstreamProject>
            <upstreamUrl>job/java-deploy-job/</upstreamUrl>
            <upstreamBuild>1</upstreamBuild>
            <upstreamCauses>
              <hudson.model.Cause_-UpstreamCause>
                <upstreamProject>java-build-job</upstreamProject>
                <upstreamUrl>job/java-build-job/</upstreamUrl>
                <upstreamBuild>10</upstreamBuild>
                <upstreamCauses>
                  <hudson.model.Cause_-UserIdCause>
                    <userId>Ranjan</userId>
                  </hudson.model.Cause_-UserIdCause>
                </upstreamCauses>
              </hudson.model.Cause_-UpstreamCause>
            </upstreamCauses>
          </hudson.model.Cause_-UpstreamCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <jenkins.metrics.impl.TimeInQueueAction plugin="metrics@4.2.37-494.v06f9a_939d33a_">
      <queuingDurationMillis>9946</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>3</buildableDurationMillis>
      <waitingDurationMillis>9941</waitingDurationMillis>
    </jenkins.metrics.impl.TimeInQueueAction>
  </actions>
  <queueId>12</queueId>
  <timestamp>1781001319056</timestamp>
  <startTime>1781001319060</startTime>
  <result>FAILURE</result>
  <duration>40</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>/var/lib/jenkins/workspace/java-test-job</workspace>
  <hudsonVersion>2.555.2</hudsonVersion>
  <scm class="hudson.scm.NullChangeLogParser"/>
  <culprits class="java.util.Collections$UnmodifiableSet">
    <c class="sorted-set"/>
  </culprits>
</build>